version: "3.2"
services:
       database:
               image: 'mongo'
               container_name: "crce_mongodb"
               restart: always
               networks:
                       - crce
               ports:
                       - '27017:27017'
               volumes:
                       - /mongodb:/data/db
                       - ./dev-dump:/dev-dump

       metadata:
                depends_on: 
                          - database
                container_name: "crce_metadata"
                networks: 
                        - crce
                build: 
                     dockerfile: ${DEPLOY_DOCKERFILE_PATH}
                     context: .
                     args: 
                         - SERVICE_PATH_PREFIX=${METADATA_SERVICE_PATH}
                ports:
                     - "8080:8080"
                volumes:
                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro

networks:
       crce:

volumes: 
        shared-modules:
                      external: true