version: "3.2"
services:
       database:
               image: 'mongo'
               container_name: "crce_mongodb"
               restart: always
               networks:
                       - crce
               ports:
                       - '27017-27019:27017-27019'
               volumes:
                       - /mongodb:/data/db
                       - ./dev-dump:/dev-dump

       metadata:
                depends_on: 
                          - database
                container_name: "crce_metadata"
                tty: true
                networks: 
                        - crce
                build: 
                     dockerfile: ${DEPLOY_DOCKERFILE_PATH}
                     context: .
                     args: 
                         - SERVICE_PATH_PREFIX=${METADATA_SERVICE_PATH}
                ports:
                     - "8081:8080"
                volumes:
                       - ${METADATA_MODULES_VOLUME_NAME}:/home/crce/modules
                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro
                command: bash -c "cd ./deploy && bash ${PREPARE_BUNDLE_NAME} && cd ${FELIX_V_PATH} && java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar ./bin/felix.jar"
                       #command: ["cd" , "./deploy" , "bash" , "prepare_bundles.sh","cd","${FELIX_V_PATH}","java","-Xdebug" ,"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar","./bin/felix.jar" ]
#
#
#       restapi:
#                depends_on: 
#                          - database
#                          - metadata
#                container_name: "crce_rest-api"
#                networks: 
#                        - crce
#                build: 
#                     dockerfile: ${DEPLOY_DOCKERFILE_NOT_METADATA_PATH}
#                     context: .
#                     args: 
#                         - SERVICE_PATH_PREFIX=${REST_API_SERVICE_PATH}
#                ports:
#                     - "8081:8080"
#                volumes:
#                       - ${METADATA_MODULES_VOLUME_NAME}:/home/crce/metadata
#                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro

       externalextensions:
                depends_on: 
                          - database
                container_name: "crce_external-extensions"
                tty: true
                networks: 
                        - crce
                build: 
                     dockerfile: ${DEPLOY_DOCKERFILE_NOT_METADATA_PATH}
                     context: .
                     args: 
                         - SERVICE_PATH_PREFIX=${EXTERNAL_EXTENSIONS_SERVICE_PATH}
                ports:
                     - "8080:8080"
                volumes:
                       - ${METADATA_MODULES_VOLUME_NAME}:/home/crce/metadata
                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro
                command: bash -c "pwd && ls && bash ${BUILD_CODE_NAME} && cd ./deploy && bash ${PREPARE_BUNDLE_NAME} && cd ${FELIX_V_PATH} && java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar ./bin/felix.jar"
                #command: ["cd" , "./deploy" , "bash" , "prepare_bundles.sh","cd","${FELIX_V_PATH}","java","-Xdebug" ,"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar","./bin/felix.jar" ]
                
#       wsindexers:
#                depends_on: 
#                          - database
#                          - metadata
#                container_name: "crce_ws-indexers"
#                networks: 
#                        - crce
#                build: 
#                     dockerfile: ${DEPLOY_DOCKERFILE_NOT_METADATA_PATH}
#                     context: .
#                     args: 
#                         - SERVICE_PATH_PREFIX=${WS_INDEXERS_SERVICE_PATH}
#                ports:
#                     - "8083:8080"
#                volumes:
#                       - ${METADATA_MODULES_VOLUME_NAME}:/home/crce/metadata
#                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro
#
#       internalextensions:
#                depends_on: 
#                          - database
#                          - metadata
#                container_name: "crce_internal-extensions"
#                networks: 
#                        - crce
#                build: 
#                     dockerfile: ${DEPLOY_DOCKERFILE_NOT_METADATA_PATH}
#                     context: .
#                     args: 
#                         - SERVICE_PATH_PREFIX=${INTERNAL_EXTENSIONS_SERVICE_PATH}
#                ports:
#                     - "8084:8080"
#                volumes:
#                       - ${METADATA_MODULES_VOLUME_NAME}:/home/crce/metadata
#                       - ${SHARED_MODULES_VOLUME_NAME}:/home/crce/shared-modules:ro
networks:
       crce:

volumes: 
        metadata-modules:
                        external: true
                        
        shared-modules:
                      external: true