version: "3.2"
services:
       app:
                build: ./deploy
                tty: true
                depends_on:
                        - database
                ports: 
                        - "8080:8080"
                networks:
                        - crce
                volumes:
                        - felix:/felix
                        - ./build:/src/build
                        - ./core:/src/core
                        - ./deploy:/src/deploy
                        - ./modules:/src/modules
                        - ./pom:/src/pom
                        - ./third-party:/src/third-party
                        - ./pom.xml:/src/pom.xml
                        - ./build-code.sh:/src/build-code.sh

                container_name: "crce_app"
                environment: 
                        # Set environmental variable for connection string to mongodb
                        mongo_connection: mongodb://172.17.0.1:27017

       database:
               image: 'mongo'
               container_name: "crce_mongodb"
               restart: always
               networks:
                       - crce
               ports:
                       - '27017-27019:27017-27019'

               volumes:
                       - data-db:/data/db

networks:
       crce:
                        
volumes:
    felix:
    data-db:
