### JAX-RS ###

framework: jaxrs

resource_annotations:
  - javax/ws/rs/Path

endpoint_annotations:
  - javax/ws/rs/GET
  - javax/ws/rs/POST
  - javax/ws/rs/PUT
  - javax/ws/rs/DELETE
  - javax/ws/rs/HEAD
  - javax/ws/rs/OPTIONS
  - javax/ws/rs/PATCH
  - javax/ws/rs/Path

url:
  - annotation: javax/ws/rs/Path
    processing_way: from_value
    valueKeys:
      - value

produces:
  - annotation: javax/ws/rs/Produces
    processing_way: from_value
    valueKeys:
      - value

consumes:
    -
      annotation: javax/ws/rs/Consumes
      processing_way: from_value
      valueKeys:
        - value

default_http_methods: []

http_method:
  -
      annotation: javax/ws/rs/GET
      processing_way: from_name
      result: GET
  -
      annotation: javax/ws/rs/POST
      processing_way: from_name
      result: POST
  - 
      annotation: javax/ws/rs/PUT
      processing_way: from_name
      result: PUT
  - 
      annotation: javax/ws/rs/DELETE
      processing_way: from_name
      result: DELETE
  - 
      annotation: javax/ws/rs/HEAD
      processing_way: from_name
      result: HEAD
  - 
      annotation: javax/ws/rs/OPTIONS
      processing_way: from_name
      result: OPTIONS

endpoint_parameters:
   - 
       annotation: javax/ws/rs/QueryParam
       processing_way: from_name
       result: query
   - 
       annotation: javax/ws/rs/PathParam
       processing_way: from_name
       result: path
   - 
       annotation: javax/ws/rs/MatrixParam
       processing_way: from_name
       result: matrix
   -
       annotation: javax/ws/rs/FormParam
       processing_way: from_name
       result: form
   -
       annotation: javax/ws/rs/HeaderParam
       processing_way: from_name
       result: header
   -
       annotation: javax/ws/rs/CookieParam
       processing_way: from_name
       result: cookie

parameter_name:
  annotationProcessors:
    -
       annotation: javax/ws/rs/QueryParam
       processing_way: from_value
       valueKeys:
        -  value
    -
       annotation: javax/ws/rs/PathParam
       processing_way: from_value
       valueKeys:
        -  value
    -
       annotation: javax/ws/rs/MatrixParam
       processing_way: from_value
       valueKeys:
        -  value
    -
       annotation: javax/ws/rs/FormParam
       processing_way: from_value
       valueKeys:
        -  value
    -
       annotation: javax/ws/rs/HeaderParam
       processing_way: from_value
       valueKeys:
        -  value
    -
       annotation: javax/ws/rs/CookieParam
       processing_way: from_value
       valueKeys:
        -  value
  from_name: false

parameter_requirement:
# PathParam is always required
  annotationProcessors:
    -
          annotation: javax/validation/constraints/NotNull
          processing_way: from_name
          result: true
  parametersDefault: false # is not required
  fieldsDefault: false     # is not required

#parameter_datetype:
#  - ParameterConvertor:
#      processing_way: from_datetype

default_parameter_value:
   - 
       annotation: javax/ws/rs/DefaultValue
       processing_way: from_value
       valueKeys:
         -  value

cookie_name:
  annotationProcessors:
    -  annotation: javax/ws/rs/CookieParam
       processing_way: from_value
       valueKeys:
          -  value

  from_name: false

default_cookie_value:
   -
       annotation: javax/ws/rs/DefaultValue
       processing_way: from_value
       valueKeys:
         -  value

header_name:
  annotationProcessors:
    -  annotation: javax/ws/rs/HeaderParam
       processing_way: from_value
       valueKeys:
          -  value

  from_name: false

default_header_value:
   -
       annotation: javax/ws/rs/DefaultValue
       processing_way: from_value
       valueKeys:
         -  value


parameter_bean_annotations:
  - javax/ws/rs/BeanParam

body:
  withoutAnnotations: true
  annotations: []
  excludingAnnotations:
  - javax/ws/rs/BeanParam
  - javax/ws/rs/core/Context


generic_response_classes:
  - javax/ws/rs/core/Response

subresources:
  true

status_setting_methods:
  owner: javax/ws/rs/core/Response
  mapping:
    ok: 200
    badRequest: 400
    notFound: 404
    created: 201
    accepted: 202
    noContent: 204
    serverError: 500
  simpleName: status

entity_setting_methods:
   - owner: javax/ws/rs/core/Response$ResponseBuilder
     simpleName: entity
     returnType: javax/ws/rs/core/Response$ResponseBuilder
   - owner: javax/ws/rs/core/Response
     simpleName: ok
     returnType: javax/ws/rs/core/Response

status_fields:
  owner: javax/ws/rs/core/Response$Status
  mapping:
    OK: 200
    CREATED: 201
    ACCEPTED: 202
    NO_CONTENT: 204
    RESET_CONTENT: 205
    PARTIAL_CONTENT: 206
    MOVED_PERMANENTLY: 301
    FOUND: 302
    SEE_OTHER: 303
    NOT_MODIFIED: 304
    USE_PROXY: 305
    TEMPORARY_REDIRECT: 307
    BAD_REQUEST: 400
    UNAUTHORIZED: 401
    PAYMENT_REQUIRED: 402
    FORBIDDEN: 403
    NOT_FOUND: 404
    METHOD_NOT_ALLOWED: 405
    NOT_ACCEPTABLE: 406
    PROXY_AUTHENTICATION_REQUIRED: 407
    REQUEST_TIMEOUT: 408
    CONFLICT: 409
    GONE: 410
    LENGTH_REQUIRED: 411
    PRECONDITION_FAILED: 412
    REQUEST_ENTITY_TOO_LARGE: 413
    REQUEST_URI_TOO_LONG: 414
    UNSUPPORTED_MEDIA_TYPE: 415
    REQUESTED_RANGE_NOT_SATISFIABLE: 416
    EXPECTATION_FAILED: 417
    PRECONDITION_REQUIRED: 428
    TOO_MANY_REQUESTS: 429
    REQUEST_HEADER_FIELDS_TOO_LARGE: 431
    INTERNAL_SERVER_ERROR: 500
    NOT_IMPLEMENTED: 501
    BAD_GATEWAY: 502
    SERVICE_UNAVAILABLE: 503
    GATEWAY_TIMEOUT: 504
    HTTP_VERSION_NOT_SUPPORTED: 505
    NETWORK_AUTHENTICATION_REQUIRED: 511

cookie_class: javax/ws/rs/core/NewCookie

cookie_setting_method:
     owner: javax/ws/rs/core/Response$ResponseBuilder
     simpleName: cookie
     returnType: javax/ws/rs/core/Response$ResponseBuilder

header_setting_method:
   owner: javax/ws/rs/core/Response$ResponseBuilder
   simpleName: header
   returnType: javax/ws/rs/core/Response$ResponseBuilder

default_object_mime: application/xml
default_primitive_mime: text/plain


fieldParamAnnotations: true
fieldParamSetterRequired: false

exception_handler:
  annotations:
    - javax/ws/rs/ext/Provider
  interfaces:
    - javax/ws/rs/ext/ExceptionMapper
  method: toResponse




#request_filter:
#  extends: []
#  implements:
#    - javax/ws/rs/container/ContainerRequestFilter
#  annotations:
#    - javax/ws/rs/ext/Provider

#special_method_inputs:
#  annotations:
#    -  javax/ws/rs/Context
#  classes:
  #- javax/ws/rs/UriInfo
  #- javax/ws/rs/HttpHeaders

