package cz.zcu.kiv.crce.rest.client.indexer.config_v2;

public enum MethodArgType {
    ENDPOINT_DATA, RESPONSE, REQUEST_BODY, REQUEST_CALLBACK, HEADER, HEADER_TYPE, HEADER_VALUE, KEY, VALUE, HTTP_METHOD, URI_VARIABLE, URL, BASE_URL, PATH, PRODUCING, CONSUMING, UNKNOWN
}
